In [5]:
# Setup environment
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install micromlgen
!pip install scikit-learn



In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn as sc




In [33]:
from sklearn import datasets
from sklearn import svm


In [20]:
testdata = [[[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12]],[[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12],[1,2,3,4,5,6,7,8,9,10,11,12]]]
ans = [1,0]

In [22]:
for x in range(2): 
    for y in range(4): 
        for z in range(12): 
            print(testdata[x][y][z]), 
            



1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


AttributeError: 'list' object has no attribute 'shape'

In [26]:
clf = svm.SVC(gamma=0.001, C=100.)

clf.fit(testdata[-1:], ans[-1:])


ValueError: Found array with dim 3. Estimator expected <= 2.

In [27]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [28]:
print(digits.data)


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [29]:
digits.images[0]


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [34]:
clf = svm.SVC(gamma=0.001, C=100.)
    
clf.fit(digits.data[:-1], digits.target[:-1])

NameError: name 'SVC' is not defined